export const afirmacoes = [
    "Eu sou capaz de alcançar meus objetivos e superar desafios.",
    "Cada dia é uma nova oportunidade para crescer e aprender.",
    "Eu mereço ser feliz e alcançar a paz interior.",
    "Eu sou forte, resiliente e tenho o poder de transformar minha vida.",
    "Acredito no meu potencial e nas minhas habilidades.",
    "Eu sou grato pelas pequenas e grandes conquistas do meu dia.",
    "Estou no controle da minha vida e das minhas escolhas.",
    "Eu atraio coisas boas para minha vida.",
    "A cada dia, me torno uma pessoa melhor.",
    "Eu sou digno de amor e respeito.",
    "Eu sou capaz de lidar com qualquer desafio que surgir.",
    "Estou sempre evoluindo e crescendo como pessoa.",
    "Eu mereço ser bem-sucedido em tudo o que faço.",
    "Eu tenho força interior para superar qualquer dificuldade.",
    "Cada erro é uma oportunidade de aprender e melhorar.",
    "Eu sou grato por todas as bênçãos da minha vida.",
    "Eu sou capaz de alcançar grandes coisas.",
    "Eu escolho a felicidade todos os dias.",
    "Eu sou a minha maior motivação.",
    "Eu estou criando a vida que desejo.",
    "Minha mente é poderosa e cheia de potencial.",
    "Eu estou em paz com meu passado e ansioso para o meu futuro.",
    "Eu sou digno de sucesso e prosperidade.",
    "Eu sou a mudança que quero ver no mundo.",
    "Eu me amo e me aceito exatamente como sou.",
    "Eu sou capaz de transformar desafios em oportunidades.",
    "Eu sou grato por todas as experiências que moldam minha jornada.",
    "Eu sou capaz de viver a vida dos meus sonhos.",
    "Eu escolho acreditar em mim mesmo.",
    "Eu sou capaz de conquistar tudo o que desejo.",
    "Eu confio em mim e no meu processo de crescimento.",
    "Eu sou capaz de criar minha própria felicidade.",
    "Eu sou uma pessoa corajosa e destemida.",
    "Eu mereço todas as coisas boas que a vida tem a oferecer.",
    "Eu tenho o poder de criar a vida que desejo.",
    "Eu sou mais do que suficiente.",
    "Eu sou grato por minha saúde e bem-estar.",
    "Eu sou capaz de superar qualquer desafio com confiança.",
    "Eu sou um imã para positividade e sucesso.",
    "Eu sou merecedor de todas as bênçãos que estão vindo em minha direção.",
    "Eu sou capaz de enfrentar todas as situações com calma e clareza.",
    "Eu sou grato pelo amor e apoio que recebo.",
    "Eu sou digno de uma vida de felicidade e abundância.",
    "Eu sou a fonte da minha própria motivação.",
    "Eu sou uma pessoa incrível e única.",
    "Eu sou capaz de transformar meus sonhos em realidade.",
    "Eu sou uma pessoa de sucesso e vou continuar a ter sucesso.",
    "Eu sou digno de tudo o que desejo e preciso em minha vida.",
    "Eu sou a minha maior prioridade e cuido de mim mesmo.",
    "Eu sou grato por ter a oportunidade de crescer e melhorar.",
    "Eu sou capaz de realizar todos os meus objetivos.",
    "Eu sou uma pessoa positiva e atraio coisas boas.",
    "Eu sou capaz de tomar decisões sábias e confiantes.",
    "Eu sou grato por cada momento da minha vida.",
    "Eu sou capaz de fazer mudanças positivas na minha vida.",
    "Eu sou cheio de energia e motivação.",
    "Eu sou digno de um futuro brilhante e próspero.",
    "Eu sou uma pessoa cheia de paz e tranquilidade.",
    "Eu sou grato por cada nova experiência que a vida me oferece.",
    "Eu sou capaz de superar qualquer coisa que me impeça de ser feliz.",
    "Eu sou mais forte do que qualquer desafio que enfrento.",
    "Eu sou capaz de alcançar a harmonia entre minha mente, corpo e espírito.",
    "Eu sou grato por todas as oportunidades que a vida me oferece.",
    "Eu sou capaz de fazer mudanças poderosas em minha vida.",
    "Eu sou um magneto de oportunidades e experiências positivas.",
    "Eu sou grato por minha mente criativa e aberta.",
    "Eu sou capaz de alcançar meu potencial ilimitado.",
    "Eu sou digno de amor, respeito e sucesso.",
    "Eu sou uma pessoa positiva que irradia luz e amor.",
    "Eu sou grato por meu trabalho e pelo impacto que ele tem na minha vida.",
    "Eu sou capaz de encontrar paz interior em qualquer situação.",
    "Eu sou capaz de fazer escolhas que me ajudam a crescer.",
    "Eu sou digno de um futuro cheio de alegria e felicidade.",
    "Eu sou um ser em constante evolução.",
    "Eu sou capaz de manter a calma e a clareza em todas as situações.",
    "Eu sou grato por minha força interior e resiliência.",
    "Eu sou capaz de aprender com meus erros e usá-los para crescer.",
    "Eu sou uma pessoa que atrai apenas coisas boas para minha vida.",
    "Eu sou capaz de viver de maneira equilibrada e harmoniosa.",
    "Eu sou grato por tudo o que a vida me proporciona.",
    "Eu sou capaz de criar mudanças positivas em minha vida.",
    "Eu sou um ser poderoso e criativo.",
    "Eu sou capaz de manter minha paz interior, independentemente das circunstâncias.",
    "Eu sou grato por minha capacidade de ver o bem em tudo.",
    "Eu sou digno de tudo o que desejo alcançar.",
    "Eu sou capaz de fazer minha vida mais feliz e gratificante.",
    "Eu sou uma pessoa positiva e atrativa.",
    "Eu sou capaz de conquistar grandes coisas com perseverança.",
    "Eu sou digno de amor, sucesso e abundância.",
    "Eu sou uma pessoa confiante e cheia de energia positiva.",
    "Eu sou capaz de criar a vida que desejo viver.",
    "Eu sou grato por minha mente criativa e expansiva.",
    "Eu sou capaz de superar qualquer situação com sabedoria e coragem.",
    "Eu sou grato por todas as lições que a vida me ensina.",
    "Eu sou capaz de manter a paz interior, independentemente de circunstâncias externas.",
    "Eu sou uma pessoa digna de um futuro brilhante e próspero.",
    "Eu sou capaz de mudar minha vida para melhor.",
    "Eu sou grato por todos os meus dons e talentos.",
    "Eu sou capaz de alcançar todos os meus objetivos com determinação.",
    "Eu sou digno de um futuro cheio de felicidade e realização."
];